// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-protocols.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var PROTOCOLS = [
  { id: "mcp", name: "Anthropic MCP", description: "Model Context Protocol for tool-using assistants." },
  { id: "acp", name: "Stripe ACP", description: "Agent Commerce Protocol for agent checkout." },
  { id: "ap2", name: "Google AP2", description: "Agent Payments Protocol." },
  { id: "ucp", name: "Google UCP", description: "Unified Commerce Protocol." },
  { id: "tap", name: "Visa TAP", description: "Token Auth Protocol for card credentials." },
  { id: "openapi", name: "OpenAPI", description: "REST-standard integration surface." }
];
var list_protocols_default = defineTool({
  name: "list_supported_protocols",
  title: "List supported protocols",
  description: "Return the agentic-commerce protocols Parleo ships on (MCP, ACP, AP2, UCP, TAP, OpenAPI).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PROTOCOLS, null, 2) }],
    structuredContent: { protocols: PROTOCOLS }
  })
});

// src/lib/mcp/tools/list-integrations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var INTEGRATIONS = [
  { name: "MCP", category: "protocol", description: "Model Context Protocol" },
  { name: "OpenAPI", category: "protocol", description: "REST standard" },
  { name: "ACP", category: "protocol", description: "Agent Commerce Protocol" },
  { name: "AP2", category: "protocol", description: "Agent Payments Protocol" },
  { name: "UCP", category: "protocol", description: "Google Unified Commerce" },
  { name: "Visa TAP", category: "protocol", description: "Token Auth Protocol" },
  { name: "Shopify", category: "platform", description: "Commerce platform" },
  { name: "Stripe", category: "payments", description: "Payments" },
  { name: "Oracle", category: "enterprise", description: "Enterprise stack" }
];
var list_integrations_default = defineTool2({
  name: "list_integrations",
  title: "List Parleo integrations",
  description: "Return the merchant, protocol, and platform integrations Parleo supports. Optionally filter by category.",
  inputSchema: {
    category: z.enum(["protocol", "platform", "payments", "enterprise"]).optional().describe("Filter by integration category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? INTEGRATIONS.filter((i) => i.category === category) : INTEGRATIONS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { integrations: items }
    };
  }
});

// src/lib/mcp/tools/enrich-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var enrich_product_default = defineTool3({
  name: "enrich_product",
  title: "Enrich product with true cost",
  description: "Demo of Parleo's incentive intelligence layer. Given a merchant and product context, returns a mock true-cost breakdown (loyalty, card offers, effective price). Uses deterministic sample data \u2014 not live merchant pricing.",
  inputSchema: {
    merchant_id: z2.string().describe("Merchant identifier, e.g. 'nike_us', 'sephora_us'."),
    product_sku: z2.string().describe("Product SKU or identifier."),
    list_price: z2.number().positive().describe("Advertised list price in USD."),
    card_signal: z2.string().optional().describe("Optional card context, e.g. 'amex_plat', 'chase_sapphire'."),
    loyalty_tier: z2.string().optional().describe("Optional loyalty tier, e.g. 'vip', 'gold'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ merchant_id, product_sku, list_price, card_signal, loyalty_tier }) => {
    const incentives = [];
    if (loyalty_tier) incentives.push({ source: "loyalty", label: `${loyalty_tier} tier reward`, amount: -Math.round(list_price * 0.1 * 100) / 100 });
    if (card_signal) incentives.push({ source: "card", label: `${card_signal} statement credit`, amount: -20 });
    incentives.push({ source: "merchant", label: "Base promo", amount: -Math.round(list_price * 0.05 * 100) / 100 });
    const discount = incentives.reduce((sum, i) => sum + i.amount, 0);
    const true_cost = Math.max(0, Math.round((list_price + discount) * 100) / 100);
    const result = {
      merchant_id,
      product_sku,
      list_price,
      incentives,
      true_cost,
      currency: "USD",
      pii: false,
      latency_ms: 48,
      note: "Demo response with sample incentive logic."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "parleo-mcp",
  title: "Parleo",
  version: "0.1.0",
  instructions: "Parleo is the incentive intelligence layer for agentic commerce. Use these tools to look up supported protocols and integrations, and to see a demo of true-cost enrichment (loyalty, card offers, effective price) for a product. Data returned by enrich_product is illustrative sample data, not live merchant pricing.",
  tools: [list_protocols_default, list_integrations_default, enrich_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
